### ISSUE TITLE
Expose actions/upload-artifact if-no-files-found parameter

### ISSUE THREAD

**Issue by SamStephens** [actions/upload-pages-artifact#24]
It'd be nice to be able to set the `actions/upload-artifact` parameter `if-no-files-found` to `error`, so that if something goes wrong during site generation and no files are created, the action fails.

**Comment by JamesMGreene** [comment]
@SamStephens Great idea! I've made a PR for that: https://github.com/actions/upload-pages-artifact/pull/55

**Comment by JamesMGreene** [comment]
This has been released in `v1.0.8`, as well as in the latest update of the `v1` major tag. 🚀

**Comment by daniel-mizsak** [comment]
@JamesMGreene Is there a specific reason for "hardcoding" the `error` value for the `if-no-files-found` parameter? I would have assumed that exposing this parameter meant that it will be an input of this action as well.

I think it makes sense making the default value stricter than the original [upload-artifact](https://github.com/actions/upload-artifact) action, but the option to set it `warn`, `error` or `ignore` could be nice here too. :)

**Comment by JamesMGreene** [comment]
@daniel-mizsak Fair question. Conceptually, a Pages deployment _without_ an artifact is a failure, so always treating a lack of deployable files as an error aligns with the product's expected outcome.

**Comment by daniel-mizsak** [comment]
@JamesMGreene I would like to have that small functionality. Is this a change that I could make a PR from or should I look into alternative solutions?

**Comment by JamesMGreene** [comment]
I can't speak authoritatively for the Pages team right now as I've since loved to another team at GitHub, but my understanding is that any changes right now would probably be limited to security vulnerabilities.

If you are running into failing builds/deploys that you don't want to fail, you can likely work around them by using some established Actions workflow techniques like [`continue-on-error: true`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) combined with [status checks](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions) like `if: ${{ failure() }}`, etc.

@yoannchaudet Any different official answer from current team?

**Comment by daniel-mizsak** [comment]
I used to do something similar, but this input parameter just feels more elegant. Maybe I will accidentally continue of a different error? Haha, not sure. :')

Will see what the official answer will be.

Thank you very much for your help! :)
